# A generic, single database configuration for Alembic.

[alembic]
script_location = alembic
prepend_sys_path = .
version_locations = %(here)s/alembic/versions

# template used to generate migration file names; The default is %%(rev)s_%%(slug)s
file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
sys_path = .

sqlalchemy.url = sqlite:///./trustlayer.db

[post_write_hooks]

[logging]
default_level = INFO

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
