"""initial_schema

Revision ID: b4d7525065b0
Revises: 
Create Date: 2026-10-03 08:03:54.182020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d7525065b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('distinct_users', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('sample_snippet', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signature', name='uq_campaign_signature')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaigns_signature'), ['signature'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('input_type', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_snippet', sa.Text(), nullable=False),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('threat_type', sa.String(length=64), nullable=False),
    sa.Column('ml_score', sa.Float(), nullable=True),
    sa.Column('rule_score', sa.Float(), nullable=True),
    sa.Column('intel_score', sa.Float(), nullable=True),
    sa.Column('url_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('explanation_source', sa.String(length=16), nullable=False),
    sa.Column('engine_breakdown', sa.JSON(), nullable=True),
    sa.Column('campaign_signature', sa.String(length=64), nullable=True),
    sa.Column('campaign_flagged', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_request_id', name='uq_analysis_user_request')
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_campaign_signature'), ['campaign_signature'], unique=False)
        batch_op.create_index('ix_analyses_campaign_user', ['campaign_signature', 'user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_client_request_id'), ['client_request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_id'), ['id'], unique=False)
        batch_op.create_index('ix_analyses_risk_created', ['risk_level', 'created_at'], unique=False)
        batch_op.create_index('ix_analyses_user_created', ['user_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_user_id'), ['user_id'], unique=False)

    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_id'), ['id'], unique=False)

    op.create_table('se_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=False),
    sa.Column('technique', sa.String(length=64), nullable=False),
    sa.Column('intensity', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('se_findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_se_findings_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_se_findings_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('se_findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_se_findings_id'))
        batch_op.drop_index(batch_op.f('ix_se_findings_analysis_id'))

    op.drop_table('se_findings')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_id'))
        batch_op.drop_index(batch_op.f('ix_indicators_analysis_id'))

    op.drop_table('indicators')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_user_id'))
        batch_op.drop_index('ix_analyses_user_created')
        batch_op.drop_index('ix_analyses_risk_created')
        batch_op.drop_index(batch_op.f('ix_analyses_id'))
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_analyses_content_hash'))
        batch_op.drop_index(batch_op.f('ix_analyses_client_request_id'))
        batch_op.drop_index('ix_analyses_campaign_user')
        batch_op.drop_index(batch_op.f('ix_analyses_campaign_signature'))

    op.drop_table('analyses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_signature'))
        batch_op.drop_index(batch_op.f('ix_campaigns_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
