"""Model training: TF-IDF (word + char n-grams) + Logistic Regression.

Trains on ml/data/dataset.csv (generated by generate_dataset.py), evaluates on
a held-out stratified split, and saves the pipeline to
ml/models/scam_model.joblib for the NLP service.

Usage:
    python -m ml.training.train_model
"""
import csv
import time
from pathlib import Path

import joblib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import train_test_split
from sklearn.pipeline import FeatureUnion, Pipeline

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "dataset.csv"
MODELS_DIR = ROOT / "models"
MODEL_PATH = MODELS_DIR / "scam_model.joblib"


def load_dataset():
    texts, labels = [], []
    with open(DATA, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            texts.append(row["text"])
            labels.append(1 if row["label"] == "scam" else 0)
    return texts, labels


def build_pipeline() -> Pipeline:
    features = FeatureUnion([
        ("word", TfidfVectorizer(ngram_range=(1, 2), sublinear_tf=True,
                                 min_df=2, max_features=20000)),
        ("char", TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5),
                                 sublinear_tf=True, min_df=2, max_features=30000)),
    ])
    clf = LogisticRegression(C=4.0, max_iter=1000, class_weight="balanced")
    return Pipeline([("features", features), ("clf", clf)])


def main() -> None:
    texts, labels = load_dataset()
    X_tr, X_te, y_tr, y_te = train_test_split(
        texts, labels, test_size=0.2, stratify=labels, random_state=42)

    pipe = build_pipeline()
    t0 = time.perf_counter()
    pipe.fit(X_tr, y_tr)
    train_time = time.perf_counter() - t0

    t1 = time.perf_counter()
    proba = pipe.predict_proba(X_te)[:, 1]
    infer_total = time.perf_counter() - t1
    preds = (proba >= 0.5).astype(int)

    metrics = {
        "accuracy": accuracy_score(y_te, preds),
        "precision": precision_score(y_te, preds),
        "recall": recall_score(y_te, preds),
        "f1": f1_score(y_te, preds),
        "roc_auc": roc_auc_score(y_te, proba),
        "train_seconds": round(train_time, 2),
        "avg_latency_ms": round(infer_total / len(X_te) * 1000, 3),
        "train_size": len(X_tr),
        "test_size": len(X_te),
    }

    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    joblib.dump(pipe, MODEL_PATH)

    print("Model saved:", MODEL_PATH)
    for k, v in metrics.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
